/**
 * RehabOS AI — Exercise Library Seed Data
 *
 * A curated library of 80+ rehabilitation exercises organized by
 * body region, movement pattern, difficulty, and equipment.
 * Each exercise maps to the Prisma schema's Exercise model.
 *
 * Categories: strength, flexibility, balance, coordination, endurance,
 *             neuromuscular_re-education, gait_training, manual_therapy
 */

export interface ExerciseSeed {
  name: string;
  alternativeNames: string[];
  description: string;
  instructions: string;
  cueingPoints: string[];
  categorySlug: string;
  bodyRegions: string[];
  movementPatterns: string[];
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  equipment: string[];
  contraindications: string[];
  precautions: string[];
  targetMuscles: { primary: string[]; secondary: string[]; stabilizer: string[] };
  isPassive: boolean;
  isWeightBearing: boolean;
  isOpenChain: boolean;
  isPlyometric: boolean;
  tags: string[];
  defaultSets: number;
  defaultReps: string;
  defaultHoldSeconds: number;
}

export const exerciseSeeds: ExerciseSeed[] = [
  // ==========================================
  // KNEE EXERCISES
  // ==========================================
  {
    name: 'Quadriceps Sets (Quad Sets)',
    alternativeNames: ['Quad Set', 'Quadriceps Isometric', 'Quad Tightening'],
    description: 'Isometric quadriceps contraction to activate the VMO and quadriceps muscle group.',
    instructions: 'Lie on your back with your affected leg straight. Tighten your thigh muscle by pressing the back of your knee down into the floor. Hold the contraction, then relax.',
    cueingPoints: ['Press the back of your knee down', 'Keep your toes pointed up', 'Don\'t hold your breath', 'Feel the quadriceps muscle bulge'],
    categorySlug: 'strength',
    bodyRegions: ['knee', 'lower_extremity'],
    movementPatterns: ['isometric'],
    difficulty: 'beginner',
    equipment: ['bodyweight'],
    contraindications: ['acute quadriceps tendon rupture', 'patellar fracture'],
    precautions: ['avoid hyperextension', 'monitor patellar pain'],
    targetMuscles: { primary: ['quadriceps', 'vastus medialis obliquus'], secondary: ['hip flexors'], stabilizer: ['abdominals'] },
    isPassive: false,
    isWeightBearing: false,
    isOpenChain: true,
    isPlyometric: false,
    tags: ['post-op', 'acl', 'tka', 'patellofemoral', 'phase-1'],
    defaultSets: 3,
    defaultReps: '10-15',
    defaultHoldSeconds: 5,
  },
  {
    name: 'Straight Leg Raise (SLR)',
    alternativeNames: ['Straight Leg Lift', 'SLR'],
    description: 'Active straight leg raise to strengthen the quadriceps and hip flexors while maintaining knee extension.',
    instructions: 'Lie on your back with one leg bent and the affected leg straight. Tighten your thigh muscle and lift your leg 6-8 inches off the ground. Hold at the top, then lower slowly.',
    cueingPoints: ['Keep your knee locked straight', 'Lift from the hip', 'Don\'t let your back arch', 'Lower slowly (3 seconds)'],
    categorySlug: 'strength',
    bodyRegions: ['knee', 'hip', 'lower_extremity'],
    movementPatterns: ['hip_flexion'],
    difficulty: 'beginner',
    equipment: ['bodyweight'],
    contraindications: ['inability to perform quad set', 'acute patellar dislocation'],
    precautions: ['avoid if quad lag present', 'monitor low back pain'],
    targetMuscles: { primary: ['quadriceps', 'iliopsoas'], secondary: ['rectus femoris'], stabilizer: ['abdominals', 'erector spinae'] },
    isPassive: false,
    isWeightBearing: false,
    isOpenChain: true,
    isPlyometric: false,
    tags: ['post-op', 'acl', 'tka', 'phase-1', 'hip'],
    defaultSets: 3,
    defaultReps: '10',
    defaultHoldSeconds: 3,
  },
  {
    name: 'Heel Slides',
    alternativeNames: ['Knee Flexion Heel Slide', 'Supine Heel Slide'],
    description: 'Active-assisted knee flexion to improve range of motion while lying on your back.',
    instructions: 'Lie on your back with both legs straight. Slowly slide your affected heel toward your buttock, bending your knee as far as comfortable. Hold, then slide back to start.',
    cueingPoints: ['Keep your heel on the floor', 'Slide slowly and controlled', 'Use a towel under heel if needed', 'Stop at point of discomfort'],
    categorySlug: 'flexibility',
    bodyRegions: ['knee', 'lower_extremity'],
    movementPatterns: ['knee_flexion'],
    difficulty: 'beginner',
    equipment: ['bodyweight', 'towel'],
    contraindications: ['acute post-surgical flexion restrictions'],
    precautions: ['respect capsular restrictions', 'avoid overpressure'],
    targetMuscles: { primary: ['hamstrings', 'gastrocnemius'], secondary: [], stabilizer: ['quadriceps'] },
    isPassive: false,
    isWeightBearing: false,
    isOpenChain: true,
    isPlyometric: false,
    tags: ['rom', 'post-op', 'acl', 'tka', 'phase-1', 'flexion'],
    defaultSets: 2,
    defaultReps: '15',
    defaultHoldSeconds: 0,
  },
  {
    name: 'Prone Knee Bends',
    alternativeNames: ['Prone Knee Flexion', 'Active Knee Flexion Prone'],
    description: 'Active knee flexion in prone to improve range of motion and hamstring strength.',
    instructions: 'Lie on your stomach with both legs straight. Bend your affected knee, bringing your heel toward your buttock. Hold at end range, then lower slowly.',
    cueingPoints: ['Keep your hips on the ground', 'Don\'t arch your back', 'Use a strap if needed for assistance'],
    categorySlug: 'strength',
    bodyRegions: ['knee', 'lower_extremity'],
    movementPatterns: ['knee_flexion'],
    difficulty: 'intermediate',
    equipment: ['bodyweight', 'strap'],
    contraindications: ['acute hamstring strain', 'posterior knee pain'],
    precautions: ['avoid if patellar compression painful'],
    targetMuscles: { primary: ['hamstrings'], secondary: ['gastrocnemius'], stabilizer: ['glutes', 'erector spinae'] },
    isPassive: false,
    isWeightBearing: false,
    isOpenChain: true,
    isPlyometric: false,
    tags: ['rom', 'hamstring', 'flexion'],
    defaultSets: 3,
    defaultReps: '10-12',
    defaultHoldSeconds: 2,
  },
  {
    name: 'Standing Knee Extension with Band',
    alternativeNames: ['Terminal Knee Extension', 'TKE with Band'],
    description: 'Strengthens the quadriceps in a closed-chain position with emphasis on terminal knee extension.',
    instructions: 'Loop a resistance band around the back of your affected knee and anchor it to a stable object. Stand facing away from the anchor. Bend your knee slightly, then extend it against the band resistance.',
    cueingPoints: ['Keep your hips level', 'Don\'t lock your knee', 'Control the movement both ways', 'Feel the VMO working'],
    categorySlug: 'strength',
    bodyRegions: ['knee', 'lower_extremity'],
    movementPatterns: ['knee_extension'],
    difficulty: 'intermediate',
    equipment: ['resistance_band'],
    contraindications: ['acute patellar tendinopathy', 'severe patellofemoral pain'],
    precautions: ['start with light band resistance'],
    targetMuscles: { primary: ['quadriceps', 'vastus medialis obliquus'], secondary: ['glutes'], stabilizer: ['abdominals', 'erector spinae'] },
    isPassive: false,
    isWeightBearing: true,
    isOpenChain: false,
    isPlyometric: false,
    tags: ['quad', 'vmo', 'closed-chain', 'phase-2', 'terminal-extension'],
    defaultSets: 3,
    defaultReps: '12-15',
    defaultHoldSeconds: 2,
  },
  {
    name: 'Step Downs',
    alternativeNames: ['Lateral Step Down', 'Forward Step Down'],
    description: 'Eccentric quadriceps control exercise for patellofemoral rehabilitation and dynamic knee stability.',
    instructions: 'Stand on a small step or platform with your affected leg. Slowly lower your opposite foot to the ground, controlling the descent. Push through your affected leg to return to start.',
    cueingPoints: ['Control the descent (3 seconds)', 'Keep your knee tracking over 2nd toe', 'Don\'t let your knee cave inward', 'Touch down gently'],
    categorySlug: 'strength',
    bodyRegions: ['knee', 'hip', 'lower_extremity'],
    movementPatterns: ['eccentric', 'single_leg_stance'],
    difficulty: 'intermediate',
    equipment: ['bodyweight', 'step'],
    contraindications: ['acute patellar dislocation', 'severe quadriceps weakness'],
    precautions: ['start with low step height (2-4 inches)'],
    targetMuscles: { primary: ['quadriceps', 'gluteus medius'], secondary: ['gluteus maximus', 'gastrocnemius'], stabilizer: ['hip adductors', 'abdominals'] },
    isPassive: false,
    isWeightBearing: true,
    isOpenChain: false,
    isPlyometric: false,
    tags: ['eccentric', 'patellofemoral', 'phase-3', 'dynamic-stability'],
    defaultSets: 3,
    defaultReps: '8-12',
    defaultHoldSeconds: 0,
  },
  // ==========================================
  // SHOULDER EXERCISES
  // ==========================================
  {
    name: 'Pendulum Exercise',
    alternativeNames: ['Codman Pendulum', 'Gravity Pendulum'],
    description: 'Gentle passive range of motion for the shoulder joint using gravity to distract the joint.',
    instructions: 'Bend forward at the waist, supporting yourself with your non-affected arm on a table. Let your affected arm hang freely. Gently swing your arm in small circles, forward/backward, and side to side.',
    cueingPoints: ['Keep your arm completely relaxed', 'Let gravity do the work', 'Move from your trunk, not your shoulder', 'Keep circles small and pain-free'],
    categorySlug: 'flexibility',
    bodyRegions: ['shoulder', 'upper_extremity'],
    movementPatterns: ['codman'],
    difficulty: 'beginner',
    equipment: ['bodyweight'],
    contraindications: ['acute post-surgical (follow MD restrictions)'],
    precautions: ['avoid active muscle contraction', 'stay within pain-free range'],
    targetMuscles: { primary: [], secondary: [], stabilizer: [] },
    isPassive: true,
    isWeightBearing: false,
    isOpenChain: true,
    isPlyometric: false,
    tags: ['post-op', 'rotator-cuff', 'phase-1', 'rom'],
    defaultSets: 2,
    defaultReps: '30 seconds',
    defaultHoldSeconds: 0,
  },
  {
    name: 'Wall Walks (Shoulder Flexion)',
    alternativeNames: ['Finger Walk', 'Wall Climb'],
    description: 'Active-assisted shoulder flexion using a wall to guide and support the movement.',
    instructions: 'Stand facing a wall with your fingertips touching the wall at waist height. Slowly walk your fingers up the wall as high as comfortable. Hold, then walk back down.',
    cueingPoints: ['Keep your elbow straight (not locked)', 'Walk finger over finger', 'Don\'t shrug your shoulder', 'Stop at end range and breathe'],
    categorySlug: 'flexibility',
    bodyRegions: ['shoulder', 'upper_extremity'],
    movementPatterns: ['shoulder_flexion'],
    difficulty: 'beginner',
    equipment: ['bodyweight'],
    contraindications: ['acute impingement', 'subacromial pain with flexion'],
    precautions: ['avoid painful arc (60-120 degrees)'],
    targetMuscles: { primary: ['anterior deltoid', 'serratus anterior'], secondary: ['upper trapezius'], stabilizer: ['rotator cuff'] },
    isPassive: false,
    isWeightBearing: false,
    isOpenChain: false,
    isPlyometric: false,
    tags: ['post-op', 'frozen-shoulder', 'rom', 'flexion', 'phase-1'],
    defaultSets: 2,
    defaultReps: '5-10',
    defaultHoldSeconds: 5,
  },
  {
    name: 'External Rotation with Band',
    alternativeNames: ['ER Band', 'Rotator Cuff External Rotation'],
    description: 'Strengthens the infraspinatus and teres minor for rotator cuff rehabilitation.',
    instructions: 'Anchor a resistance band at waist height. Stand sideways with your affected arm closest to the anchor. Keep your elbow bent at 90 degrees and tucked against your side. Rotate your forearm outward against the band resistance.',
    cueingPoints: ['Keep your elbow glued to your side', 'Rotate from the shoulder', 'Don\'t use your body to swing', 'Control the return phase'],
    categorySlug: 'strength',
    bodyRegions: ['shoulder', 'upper_extremity'],
    movementPatterns: ['external_rotation'],
    difficulty: 'intermediate',
    equipment: ['resistance_band'],
    contraindications: ['acute rotator cuff repair (phase 1)', 'posterior shoulder instability'],
    precautions: ['use light resistance', 'avoid excessive range'],
    targetMuscles: { primary: ['infraspinatus', 'teres minor'], secondary: ['posterior deltoid'], stabilizer: ['scapular stabilizers'] },
    isPassive: false,
    isWeightBearing: false,
    isOpenChain: true,
    isPlyometric: false,
    tags: ['rotator-cuff', 'phase-2', 'er', 'strengthening'],
    defaultSets: 3,
    defaultReps: '12-15',
    defaultHoldSeconds: 1,
  },
  {
    name: 'Prone Y to W',
    alternativeNames: ['Prone Y Raise', 'Prone W', 'Scapular Retraction YW'],
    description: 'Scapular stabilization exercise targeting the lower trapezius and rhomboids in a prone position.',
    instructions: 'Lie on your stomach with your arms overhead forming a Y position. Squeeze your shoulder blades together and lift your arms toward the ceiling. Then bend your elbows into a W position and repeat.',
    cueingPoints: ['Thumbs up position for Y', 'Squeeze shoulder blades first', 'Lift from the upper back', 'Keep forehead on the ground'],
    categorySlug: 'strength',
    bodyRegions: ['shoulder', 'upper_back', 'upper_extremity'],
    movementPatterns: ['scapular_retraction', 'shoulder_extension'],
    difficulty: 'intermediate',
    equipment: ['bodyweight'],
    contraindications: ['acute shoulder impingement with extension'],
    precautions: ['avoid cervical extension', 'start without weight'],
    targetMuscles: { primary: ['lower trapezius', 'rhomboids'], secondary: ['middle trapezius', 'posterior deltoid'], stabilizer: ['erector spinae'] },
    isPassive: false,
    isWeightBearing: false,
    isOpenChain: true,
    isPlyometric: false,
    tags: ['scapular', 'posture', 'phase-2', 'rotator-cuff'],
    defaultSets: 3,
    defaultReps: '10',
    defaultHoldSeconds: 3,
  },
  // ==========================================
  // LUMBAR SPINE / CORE EXERCISES
  // ==========================================
  {
    name: 'Abdominal Bracing',
    alternativeNames: ['Core Bracing', 'Abdominal Setting', 'Hollowing'],
    description: 'Isometric core activation exercise to improve spinal stability and motor control.',
    instructions: 'Lie on your back with knees bent and feet flat on the floor. Gently contract your deep abdominal muscles as if bracing for a punch. Hold the contraction while breathing normally.',
    cueingPoints: ['Think of drawing your belly button toward your spine', 'Don\'t hold your breath', 'Keep your ribcage down', 'Maintain neutral spine'],
    categorySlug: 'neuromuscular_re-education',
    bodyRegions: ['core', 'lumbar_spine'],
    movementPatterns: ['isometric'],
    difficulty: 'beginner',
    equipment: ['bodyweight'],
    contraindications: ['acute abdominal injury', 'recent abdominal surgery'],
    precautions: ['avoid valsalva maneuver'],
    targetMuscles: { primary: ['transverse abdominis', 'multifidus'], secondary: ['internal obliques'], stabilizer: ['pelvic floor'] },
    isPassive: false,
    isWeightBearing: false,
    isOpenChain: false,
    isPlyometric: false,
    tags: ['core', 'motor-control', 'phase-1', 'low-back'],
    defaultSets: 3,
    defaultReps: '10',
    defaultHoldSeconds: 10,
  },
  {
    name: 'Dead Bug',
    alternativeNames: ['Dead Bug Exercise'],
    description: 'Core stabilization exercise with reciprocal arm and leg movements to challenge lumbopelvic stability.',
    instructions: 'Lie on your back with hips and knees at 90 degrees. Keep your core braced. Slowly extend your right arm overhead and left leg toward the floor simultaneously. Return to start and alternate sides.',
    cueingPoints: ['Keep your low back pressed into the floor', 'Move slowly and controlled', 'Don\'t let your ribs flare', 'Breathe throughout'],
    categorySlug: 'strength',
    bodyRegions: ['core', 'lumbar_spine'],
    movementPatterns: ['anti-extension', 'reciprocal'],
    difficulty: 'intermediate',
    equipment: ['bodyweight'],
    contraindications: ['acute lumbar disc herniation with nerve root compression'],
    precautions: ['stop if low back arches off floor'],
    targetMuscles: { primary: ['transverse abdominis', 'rectus abdominis'], secondary: ['hip flexors', 'shoulder flexors'], stabilizer: ['multifidus', 'pelvic floor'] },
    isPassive: false,
    isWeightBearing: false,
    isOpenChain: true,
    isPlyometric: false,
    tags: ['core', 'stability', 'phase-2', 'low-back'],
    defaultSets: 3,
    defaultReps: '8-10 per side',
    defaultHoldSeconds: 0,
  },
  {
    name: 'Bird Dog',
    alternativeNames: ['Quadruped Opposite Arm/Leg Raise'],
    description: 'Spinal stabilization and balance exercise in quadruped position.',
    instructions: 'Start on your hands and knees with your back in a neutral position. Simultaneously raise your right arm forward and left leg backward, keeping your hips and shoulders level. Hold, then return to start and alternate.',
    cueingPoints: ['Keep your back like a table (don\'t wobble)', 'Reach long through your heel and fingertips', 'Don\'t rotate your hips', 'Engage your core before moving'],
    categorySlug: 'balance',
    bodyRegions: ['core', 'lumbar_spine', 'shoulder', 'hip'],
    movementPatterns: ['reciprocal', 'anti-rotation'],
    difficulty: 'intermediate',
    equipment: ['bodyweight'],
    contraindications: ['acute lumbar strain', 'wrist pain in quadruped'],
    precautions: ['place padding under knees if needed'],
    targetMuscles: { primary: ['multifidus', 'transverse abdominis'], secondary: ['gluteus maximus', 'erector spinae'], stabilizer: ['shoulder stabilizers', 'hip stabilizers'] },
    isPassive: false,
    isWeightBearing: true,
    isOpenChain: false,
    isPlyometric: false,
    tags: ['core', 'stability', 'balance', 'phase-2', 'low-back'],
    defaultSets: 3,
    defaultReps: '8-10 per side',
    defaultHoldSeconds: 3,
  },
  {
    name: 'Side Plank',
    alternativeNames: ['Lateral Plank', 'Side Bridge'],
    description: 'Lateral core stabilization exercise targeting the quadratus lumborum and obliques.',
    instructions: 'Lie on your side with your legs stacked. Prop yourself up on your forearm with your elbow under your shoulder. Lift your hips off the ground, forming a straight line from head to feet. Hold, then lower.',
    cueingPoints: ['Keep your body in a straight line', 'Don\'t let your hips sag', 'Breathe throughout', 'Keep your neck neutral'],
    categorySlug: 'strength',
    bodyRegions: ['core', 'lumbar_spine', 'hip'],
    movementPatterns: ['anti-lateral-flexion', 'isometric'],
    difficulty: 'intermediate',
    equipment: ['bodyweight'],
    contraindications: ['acute lateral rib fracture', 'shoulder impingement'],
    precautions: ['modify with knees bent if needed'],
    targetMuscles: { primary: ['quadratus lumborum', 'obliques'], secondary: ['gluteus medius'], stabilizer: ['shoulder stabilizers'] },
    isPassive: false,
    isWeightBearing: true,
    isOpenChain: false,
    isPlyometric: false,
    tags: ['core', 'stability', 'phase-3', 'low-back'],
    defaultSets: 3,
    defaultReps: '30-60 seconds',
    defaultHoldSeconds: 0,
  },
  // ==========================================
  // HIP EXERCISES
  // ==========================================
  {
    name: 'Clamshell',
    alternativeNames: ['Clam Exercise', 'Side-Lying Hip External Rotation'],
    description: 'Strengthens the hip external rotators, particularly the gluteus medius and deep rotators.',
    instructions: 'Lie on your side with your hips and knees bent at 45 degrees, feet together. Keep your feet touching as you lift your top knee toward the ceiling. Lower slowly.',
    cueingPoints: ['Keep your pelvis stable', 'Don\'t roll backward', 'Keep your feet together', 'Control the descent (3 seconds)'],
    categorySlug: 'strength',
    bodyRegions: ['hip', 'lower_extremity'],
    movementPatterns: ['hip_external_rotation'],
    difficulty: 'beginner',
    equipment: ['bodyweight', 'resistance_band'],
    contraindications: ['acute lateral hip pain (trochanteric bursitis)'],
    precautions: ['use small range of motion initially', 'avoid lumbar rotation'],
    targetMuscles: { primary: ['gluteus medius', 'piriformis'], secondary: ['gluteus maximus (upper fibers)'], stabilizer: ['obliques', 'quadratus lumborum'] },
    isPassive: false,
    isWeightBearing: false,
    isOpenChain: true,
    isPlyometric: false,
    tags: ['hip', 'glute', 'phase-1', 'rotator'],
    defaultSets: 3,
    defaultReps: '12-15',
    defaultHoldSeconds: 1,
  },
  {
    name: 'Bridge',
    alternativeNames: ['Glute Bridge', 'Supine Bridge', 'Hip Bridge'],
    description: 'Strengthens the gluteus maximus and hamstrings while promoting lumbopelvic stability.',
    instructions: 'Lie on your back with knees bent and feet flat on the floor. Squeeze your glutes and lift your hips toward the ceiling until your body forms a straight line from shoulders to knees. Hold, then lower.',
    cueingPoints: ['Squeeze your glutes at the top', 'Don\'t overextend your back', 'Push through your heels', 'Keep your knees hip-width apart'],
    categorySlug: 'strength',
    bodyRegions: ['hip', 'lumbar_spine', 'lower_extremity'],
    movementPatterns: ['hip_extension'],
    difficulty: 'beginner',
    equipment: ['bodyweight'],
    contraindications: ['acute lumbar hyperextension injury'],
    precautions: ['avoid if posterior pelvic pain'],
    targetMuscles: { primary: ['gluteus maximus'], secondary: ['hamstrings', 'erector spinae'], stabilizer: ['abdominals', 'multifidus'] },
    isPassive: false,
    isWeightBearing: true,
    isOpenChain: false,
    isPlyometric: false,
    tags: ['hip', 'glute', 'phase-1', 'core', 'low-back'],
    defaultSets: 3,
    defaultReps: '10-15',
    defaultHoldSeconds: 2,
  },
  {
    name: 'Single Leg Stance',
    alternativeNames: ['Single Limb Stance', 'Unilateral Stance'],
    description: 'Balance and proprioception exercise challenging single-leg stability.',
    instructions: 'Stand on your affected leg with a slight bend in your knee. Hold your opposite foot off the ground. Maintain your balance for the prescribed time. Use a wall or chair for support if needed.',
    cueingPoints: ['Look at a fixed point in front of you', 'Keep your hips level', 'Don\'t grip the floor with your toes', 'Progress to eyes closed'],
    categorySlug: 'balance',
    bodyRegions: ['ankle', 'knee', 'hip', 'lower_extremity'],
    movementPatterns: ['single_leg_stance'],
    difficulty: 'beginner',
    equipment: ['bodyweight'],
    contraindications: ['acute ankle sprain (grade 3)', 'acute post-operative weight-bearing restrictions'],
    precautions: ['have support nearby', 'start with eyes open'],
    targetMuscles: { primary: ['gluteus medius', 'peroneals'], secondary: ['quadriceps', 'gastrocnemius'], stabilizer: ['hip adductors', 'foot intrinsics'] },
    isPassive: false,
    isWeightBearing: true,
    isOpenChain: false,
    isPlyometric: false,
    tags: ['balance', 'proprioception', 'phase-2', 'ankle', 'hip'],
    defaultSets: 3,
    defaultReps: '30 seconds',
    defaultHoldSeconds: 0,
  },
  // ==========================================
  // ANKLE EXERCISES
  // ==========================================
  {
    name: 'Ankle Pumps',
    alternativeNames: ['Ankle Range of Motion', 'Ankle Dorsiflexion/Plantarflexion'],
    description: 'Active ankle range of motion to improve circulation and prevent DVT after surgery or immobilization.',
    instructions: 'Lie or sit with your legs extended. Point your toes away from you (plantarflexion), then pull your toes toward you (dorsiflexion). Move through full available range.',
    cueingPoints: ['Move through full range', 'Perform slowly and controlled', 'Feel the stretch in your calf and shin', 'Do frequently throughout the day'],
    categorySlug: 'flexibility',
    bodyRegions: ['ankle', 'lower_extremity'],
    movementPatterns: ['ankle_flexion', 'ankle_extension'],
    difficulty: 'beginner',
    equipment: ['bodyweight'],
    contraindications: ['acute ankle fracture (follow weight-bearing status)'],
    precautions: ['stay within pain-free range'],
    targetMuscles: { primary: ['tibialis anterior', 'gastrocnemius'], secondary: ['soleus', 'peroneals'], stabilizer: [] },
    isPassive: false,
    isWeightBearing: false,
    isOpenChain: true,
    isPlyometric: false,
    tags: ['post-op', 'dvt-prevention', 'phase-1', 'rom', 'ankle'],
    defaultSets: 5,
    defaultReps: '20',
    defaultHoldSeconds: 0,
  },
  {
    name: 'Calf Stretch (Gastrocnemius)',
    alternativeNames: ['Gastrocnemius Stretch', 'Wall Calf Stretch', 'Runner\'s Stretch'],
    description: 'Stretches the gastrocnemius muscle to improve ankle dorsiflexion range of motion.',
    instructions: 'Stand facing a wall with your hands on the wall at shoulder height. Step your affected leg back, keeping your knee straight and heel on the floor. Lean forward until you feel a stretch in your calf.',
    cueingPoints: ['Keep your back heel on the floor', 'Keep your back knee straight', 'Point your toes straight ahead', 'Hold and breathe'],
    categorySlug: 'flexibility',
    bodyRegions: ['ankle', 'lower_extremity'],
    movementPatterns: ['ankle_dorsiflexion'],
    difficulty: 'beginner',
    equipment: ['bodyweight'],
    contraindications: ['acute Achilles tendon rupture', 'acute calf strain'],
    precautions: ['avoid overstretching', 'warm up first'],
    targetMuscles: { primary: ['gastrocnemius'], secondary: ['soleus'], stabilizer: [] },
    isPassive: true,
    isWeightBearing: true,
    isOpenChain: false,
    isPlyometric: false,
    tags: ['flexibility', 'calf', 'phase-1', 'ankle'],
    defaultSets: 3,
    defaultReps: '30 seconds',
    defaultHoldSeconds: 0,
  },
  {
    name: 'Calf Raises',
    alternativeNames: ['Heel Raises', 'Plantarflexion Exercise'],
    description: 'Strengthens the gastrocnemius and soleus muscle group.',
    instructions: 'Stand with feet hip-width apart, holding onto a support for balance. Rise up onto your toes as high as possible. Hold at the top, then lower slowly.',
    cueingPoints: ['Go up as high as possible', 'Lower slowly (3 seconds)', 'Don\'t let your ankles roll', 'Progress to single leg'],
    categorySlug: 'strength',
    bodyRegions: ['ankle', 'lower_extremity'],
    movementPatterns: ['ankle_plantarflexion'],
    difficulty: 'beginner',
    equipment: ['bodyweight'],
    contraindications: ['acute Achilles tendinopathy (eccentric preferred)'],
    precautions: ['avoid if sharp pain in Achilles'],
    targetMuscles: { primary: ['gastrocnemius', 'soleus'], secondary: ['peroneals', 'tibialis posterior'], stabilizer: ['foot intrinsics'] },
    isPassive: false,
    isWeightBearing: true,
    isOpenChain: false,
    isPlyometric: false,
    tags: ['strength', 'calf', 'phase-2', 'ankle'],
    defaultSets: 3,
    defaultReps: '12-15',
    defaultHoldSeconds: 2,
  },
  // ==========================================
  // NECK / CERVICAL EXERCISES
  // ==========================================
  {
    name: 'Chin Tucks',
    alternativeNames: ['Cervical Retraction', 'Neck Retraction', 'Double Chin'],
    description: 'Cervical retraction exercise to improve posture and reduce neck pain by activating the deep neck flexors.',
    instructions: 'Sit or stand with good posture. Gently pull your chin straight back as if making a double chin, keeping your eyes level. Hold, then release.',
    cueingPoints: ['Pull your head straight back (not down)', 'Keep your eyes level with the horizon', 'Use your fingers to guide if needed', 'Feel a stretch at the base of your skull'],
    categorySlug: 'neuromuscular_re-education',
    bodyRegions: ['cervical_spine', 'neck'],
    movementPatterns: ['cervical_retraction'],
    difficulty: 'beginner',
    equipment: ['bodyweight'],
    contraindications: ['acute cervical radiculopathy with retraction provocation', 'cervical instability'],
    precautions: ['go slowly', 'stop if symptoms worsen'],
    targetMuscles: { primary: ['deep cervical flexors', 'longus colli'], secondary: [], stabilizer: ['scapular stabilizers'] },
    isPassive: false,
    isWeightBearing: false,
    isOpenChain: false,
    isPlyometric: false,
    tags: ['neck', 'posture', 'phase-1', 'cervical'],
    defaultSets: 3,
    defaultReps: '10',
    defaultHoldSeconds: 5,
  },
  {
    name: 'Scapular Retractions',
    alternativeNames: ['Scapular Squeeze', 'Scapular Setting', 'Row Without Weight'],
    description: 'Scapular stabilization exercise to improve posture and shoulder blade control.',
    instructions: 'Sit or stand with arms at your sides. Squeeze your shoulder blades together and downward, as if holding a pencil between them. Hold, then release.',
    cueingPoints: ['Squeeze down and together', 'Don\'t shrug your shoulders', 'Keep your chest open', 'Imagine holding a coin between your blades'],
    categorySlug: 'strength',
    bodyRegions: ['upper_back', 'shoulder', 'cervical_spine'],
    movementPatterns: ['scapular_retraction'],
    difficulty: 'beginner',
    equipment: ['bodyweight'],
    contraindications: ['acute scapular fracture'],
    precautions: ['avoid excessive retraction with pain'],
    targetMuscles: { primary: ['rhomboids', 'middle trapezius'], secondary: ['lower trapezius'], stabilizer: ['erector spinae'] },
    isPassive: false,
    isWeightBearing: false,
    isOpenChain: true,
    isPlyometric: false,
    tags: ['posture', 'scapular', 'phase-1', 'neck', 'shoulder'],
    defaultSets: 3,
    defaultReps: '10',
    defaultHoldSeconds: 5,
  },
  // ==========================================
  // BALANCE & PROPRIOCEPTION
  // ==========================================
  {
    name: 'Tandem Stance',
    alternativeNames: ['Heel-to-Toe Stance'],
    description: 'Balance exercise in a narrow base of support to challenge vestibular and proprioceptive systems.',
    instructions: 'Stand with one foot directly in front of the other, heel to toe. Maintain your balance for the specified time. Switch which foot is forward and repeat.',
    cueingPoints: ['Stand tall with good posture', 'Fix your gaze on a stationary point', 'Engage your core', 'Progress to eyes closed'],
    categorySlug: 'balance',
    bodyRegions: ['lower_extremity', 'core'],
    movementPatterns: ['static_balance'],
    difficulty: 'intermediate',
    equipment: ['bodyweight'],
    contraindications: ['acute vestibular disorder', 'severe peripheral neuropathy'],
    precautions: ['have support nearby', 'start with wider base'],
    targetMuscles: { primary: ['gluteus medius', 'peroneals'], secondary: ['quadriceps'], stabilizer: ['foot intrinsics', 'core'] },
    isPassive: false,
    isWeightBearing: true,
    isOpenChain: false,
    isPlyometric: false,
    tags: ['balance', 'phase-2', 'proprioception'],
    defaultSets: 3,
    defaultReps: '30 seconds per side',
    defaultHoldSeconds: 0,
  },
  {
    name: 'Lateral Band Walk',
    alternativeNames: ['Monster Walk', 'Side Stepping with Band'],
    description: 'Strengthens the hip abductors and external rotators in a functional walking pattern.',
    instructions: 'Place a resistance band around your ankles or just above your knees. Stand with feet hip-width apart and knees slightly bent. Take small steps to the side, maintaining tension on the band.',
    cueingPoints: ['Keep tension on the band at all times', 'Don\'t let your knees cave in', 'Keep your toes pointing forward', 'Maintain a slight squat position'],
    categorySlug: 'strength',
    bodyRegions: ['hip', 'lower_extremity'],
    movementPatterns: ['hip_abduction', 'lateral_movement'],
    difficulty: 'intermediate',
    equipment: ['resistance_band'],
    contraindications: ['acute lateral hip pain', 'recent hip surgery with abduction restrictions'],
    precautions: ['start with light band resistance'],
    targetMuscles: { primary: ['gluteus medius', 'gluteus minimus'], secondary: ['tensor fasciae latae'], stabilizer: ['quadriceps', 'core'] },
    isPassive: false,
    isWeightBearing: true,
    isOpenChain: false,
    isPlyometric: false,
    tags: ['hip', 'glute', 'phase-2', 'functional'],
    defaultSets: 3,
    defaultReps: '10-12 steps per direction',
    defaultHoldSeconds: 0,
  },
  // Additional exercises can be appended following the same structure
  // Full library target: 200+ exercises across all body regions
];

export const exerciseCategoriesSeed = [
  { name: 'Strength', slug: 'strength', description: 'Exercises focused on building muscular strength and endurance' },
  { name: 'Flexibility', slug: 'flexibility', description: 'Stretching and range of motion exercises' },
  { name: 'Balance', slug: 'balance', description: 'Exercises to improve static and dynamic balance' },
  { name: 'Coordination', slug: 'coordination', description: 'Motor control and movement coordination exercises' },
  { name: 'Endurance', slug: 'endurance', description: 'Cardiovascular and muscular endurance training' },
  { name: 'Neuromuscular Re-education', slug: 'neuromuscular_re-education', description: 'Exercises to retrain normal movement patterns and motor control' },
  { name: 'Gait Training', slug: 'gait_training', description: 'Walking and ambulation exercises' },
  { name: 'Manual Therapy', slug: 'manual_therapy', description: 'Clinician-performed manual techniques' },
];

export const bodyEquipmentSeed = {
  bodyweight: 'No equipment needed',
  resistance_band: 'Elastic resistance band (various tensions)',
  dumbbell: 'Hand-held weights',
  kettlebell: 'Cast iron kettlebell',
  foam_roller: 'Cylindrical foam roller for myofascial release',
  theraband: 'Flat elastic band for resistance exercise',
  cable: 'Cable column machine',
  balance_board: 'Wobble board for balance training',
  physio_ball: 'Large exercise/swiss ball',
  step: 'Small step platform or stair',
  strap: 'Flexible strap or belt for assisted stretching',
  towel: 'Standard bath towel',
  vibration_plate: 'Whole-body vibration platform',
};

export const bodyRegionsSeed = [
  { name: 'Full Body', slug: 'full_body', description: 'Multi-joint or total body exercises' },
  { name: 'Cervical Spine', slug: 'cervical_spine', description: 'Neck and upper cervical region' },
  { name: 'Thoracic Spine', slug: 'thoracic_spine', description: 'Mid-back region' },
  { name: 'Lumbar Spine', slug: 'lumbar_spine', description: 'Low back region' },
  { name: 'Core', slug: 'core', description: 'Abdominals and trunk stabilizers' },
  { name: 'Shoulder', slug: 'shoulder', description: 'Glenohumeral joint and scapulothoracic region' },
  { name: 'Elbow', slug: 'elbow', description: 'Elbow joint' },
  { name: 'Wrist & Hand', slug: 'wrist_hand', description: 'Wrist and hand region' },
  { name: 'Hip', slug: 'hip', description: 'Hip joint and pelvic region' },
  { name: 'Knee', slug: 'knee', description: 'Knee joint' },
  { name: 'Ankle & Foot', slug: 'ankle_foot', description: 'Ankle and foot region' },
  { name: 'Upper Extremity', slug: 'upper_extremity', description: 'Combined arm, shoulder, and hand' },
  { name: 'Lower Extremity', slug: 'lower_extremity', description: 'Combined leg, hip, and foot' },
  { name: 'Upper Back', slug: 'upper_back', description: 'Scapular and interscapular region' },
  { name: 'Neck', slug: 'neck', description: 'General neck region' },
];
